### ISSUE TITLE
Översättning till spanska saknas i skapa konto

### ISSUE THREAD

**Issue by CamillaKaddio2** [kaddio/platform#107]
<img width="508" alt="Skärmavbild 2024-12-18 kl  10 39 39" src="https://github.com/user-attachments/assets/f37be65f-d841-4fa1-9510-95e7c12a5236" />

**Comment by rhymn** [comment]
Fixat, verifiera i produktion att det funkar.

**Comment by CamillaKaddio2** [comment]
funkar!
