### ISSUE TITLE
footern är inte så passande för hemsidor

### ISSUE THREAD

**Issue by rhymn** [kaddio/platform#13]
Utveckla!

**Comment by rhymn** [comment]
![Image](https://github.com/kaddio/platform/assets/2833107/eb3b0771-ef1c-4892-9b0e-f1afe42abb45)

**Comment by CamillaKaddio2** [comment]
Detta är samma footer som vi har på kaddio.com. 

Utveckla gärna hur den ska förbättras

**Comment by rhymn** [comment]
Det är en marketplace-footer. Ska företaget ha en hemsida i den bemärkelsen kanske vi inte ska hänvisa till hitta-klinik på det sättet. Det sätter dem i mkt mer konkurrens än vi gör idag. Isåfall behöver det kollas av mer med befintliga kunder som har hemsida idag.

**Comment by CamillaKaddio2** [comment]
Jaha nu förstår jag, det är på respektive organisations hemsida. tänkte att det var i /hitta-klinik. 

Vi ser om @arvidkastel  kan ta bort denna i rc:n imorn. 
Bakåtpilen ska vara löst.
