### ISSUE TITLE
Customer case

### ISSUE THREAD

**Issue by rhymn** [kaddio/platform#4]
https://kaddio.com/case

**Comment by rhymn** [comment]
På hemsidan kan vi ha case: Fundera på vilka case vi har idag. exempel:

https://developer.swish.nu
https://developer.swish.nu/explore/customer-cases
https://developer.swish.nu/ticketmaster

**Comment by rhymn** [comment]
@Rongobongo komplettera gärna denna issuen med info när det finns.

**Comment by rhymn** [comment]
Ana Casanovas
Traditional meets modern in the mountains of Mallorca.
Ana Casanovas, applies hydrophobic coating to a ”fiola” (terracotta tile in Mallorquín) of that will become the windowsills of her new home.
"I have always been attracted to methods that are natural or traditional, both in my work and in my hobbies."
Ana works as an osteopath and physiotherapist since more then 20 years. She runs her own clinic, Spanda Healthcare, in the town Selva in the beautiful Tramuntana mountains of Mallorca.
"I really like working with everything that is a bout the mind-body relationship, to help people understand that it is not only biology."
While Ana's interests are strongly rooted in traditional crafts, she also has a constant lookout for the new and modern.
"I was looking for a way to make my medical records more efficient, and that is when I found Kaddio."
Watch the video to hear more about Ana's work and hobbies, and how Kaddio allows for more flexibility in her work with medical records.

BILD
Ana.png
Osteopath and physiotherapist Ana Casanovas at her clinic Spanda Healthcare in Mallorca.

Vänliga hälsningar

Daniel Heed
Kaddio AB

kaddio_logo_extra_small.png
[www.kaddio.com](http://www.kaddio.com/)

**Comment by rhymn** [comment]
Silvia Tiray
Kitesurfing as an inspiration for osteopathic work.
Silvia Tiray carefully watches the movement of the wind and waves at the xxx (namn kommer snart!) beach in Mallorca. She is about to go kitesurfing together with her husband and son.
"You must be sharp and responsive at all times", Silvia says.
Just as carefully as she watches the waves of the ocean, Silvia watches the movements and responses of her clients during osteopathic treatments.
"You know that the circumstances may change at any moment and you have to adapt to whatever will happen next."
Silvia and her husband Lluis Miguel Horta run the center Osteopatia Mallorca in Palma, Mallorca. At the end of 2022, Silvia started the transition from working with pen and paper to taking digital medical records, using Kaddio.
Watch the video to hear more about how kitesurfing inspires Silvia's daily work as an osteopath and her comparisons of old and new approaches to taking medical records.
BILD

Silvia.png
Osteopath Silvia Tiray at her center Osteopatia Mallorca.

Vänliga hälsningar

Daniel Heed
Kaddio AB

kaddio_logo_extra_small.png
[www.kaddio.com](http://www.kaddio.com/)

**Comment by rhymn** [comment]
Jag förstår inte hur vi ska använda detta. Är det vad som sägs i filmen liksom?

"Ana Casanovas, applies hydrophobic coating to a ”fiola” (terracotta tile in Mallorquín) of that will become the windowsills of her new home." Oerhört komplicerad mening 😆 Jag tror inte många människor förstår vad som står där. Den behöver vi göra enklare.

Kolla på sidorna för case och fundera kring hur denna text ska kunna användas där, vilken text ska vara var nåsonstans och vi kan inte använda "namn kommer snart!" förrän namnet finns.

**Comment by rhymn** [comment]
> @Rongobongo komplettera gärna denna issuen med info när det finns.

Vi fortsätter dialog kring detta här så att vi alla har tillgång till detta.

**Comment by rhymn** [comment]
Jag saknar film till Silvia (länk till Vimeo tack)

**Comment by rhymn** [comment]
Samt info om vad vi ska skriva att de använder i Kaddio (moduler)

**Comment by rhymn** [comment]
Texten behöver korras, finns felstavningar. Jag gör en best-effort nu.

**Comment by rhymn** [comment]
Film saknas till Ana också.

**Comment by rhymn** [comment]
Jag hittade filmer på Vimeo nu 👍

**Comment by rhymn** [comment]
Heter Silvia Tiray (mail) eller Triay (Vimeo)?

**Comment by Rongobongo** [comment]
Tog du bort min bästa mening?!?! :-) Älska "fiolas"!!

Silvia Triay (Vimeo).

**Comment by Rongobongo** [comment]
... och lägg gärna till "Sa Rápita" på Silvias text, alltså 
!Silvia Triay carefully watches the movement of the wind and waves at the **Sa Rápita** beach in Mallorca. She is about to go kitesurfing together with her husband and son.

**Comment by Rongobongo** [comment]
![image](https://github.com/kaddio/platform/assets/97586575/ed5e7349-95a8-46bb-8997-bd6538076caa)

Kanske ser det tomt ut om det enbart står "Case study"... Antingen lägg till modulerna igen såsom det var, eller ta bort. Alternativt ifall det fanns någon video-ikon, samt en penna-och-block-ikon som kan snygga till det?

Osteopatia Mallorca ska vara Osteopatía Mallorca, alltså med en apostrof över i:et på Osteopatía. 

Sen var det ju snyggt med kartnål-ikonen. Kanske ta tillbaka den?

Vi sa också att vi funderade på att kunna göra företagsnamnet klickbart? Om så är fallet kommer länkar nedan:
Silvia Triay: https://osteopatiamallorca.com
Petter Jormin: https://majornasosteopati.se
Ana Casanovas: https://www.spandahealthcare.com

Jag och Lena kollade på texterna igår, men tror vi behöver ta en kort avstämning till kring vilket språk/vad vi förmedlar osv. Kanske idag, så kan vi få allt färdigt. Detsamma gäller texten till Petter, jag har skrivit något, men tonen som vi kommer fram till idag kommer ligga till grund till min text om Petter. Men vi är på G!

Ses om en stund

**Comment by Rongobongo** [comment]
![image](https://github.com/kaddio/platform/assets/97586575/8854a8a4-9f3f-4692-9348-fcbde428ba29)

**Comment by Rongobongo** [comment]
Petter: (obs bara utkast, kommentera gärna :-))


Case study		Medical record
 Developing experience   
Petter runs two clinics in Gothenburg, Sweden. In his daily practice he meets all kinds of patients which gives him new perspectives every day.

Majornas Osteopati
Gothenburg, Sweden




Meet Petter 
Petter Jormin is inspired by the meeting of each patient. With two busy clinics he is developing a lot of experience. 
”Each patient teaches me something. By seeing all kinds of patients with all sorts of complaints I can evolve my skills in osteopathic practice every day”.   Petter graduated in 2011 from Skandinaviska Osteopathögskolan validated by the University of Wales. In the video he describes how Kaddio allows him to have more time for his patients. 


https://majornasosteopati.se/

**Comment by rhymn** [comment]
Majornas osteopati är nu nu under case. @LenaKaddio justera gärna direkt i repot.
