### ISSUE TITLE
Översätt tos, privacy policy och DPA till engelska

### ISSUE THREAD

**Issue by LenaKaddio** [kaddio/platform#55]
Översätt privacy policy till engelska.

**Comment by rhymn** [comment]
Jag tycker att vi kan ta fram en tos och en privacy på engelska sen har vi dem enbart på de språken.

**Comment by rhymn** [comment]
Även vårat DPA.

**Comment by LenaKaddio** [comment]
tos och privacy finns översatt till EN i branch rc-hemsida-sommar-ny, se även https://github.com/kaddio/kaddio/issues/6340

DPA finns översatt till EN här: https://support.kaddio.com/document/iAwHh6DDt8bqqYL68

Är inte så bra på legal english så behöver hjälp att granska.
