### ISSUE TITLE
svengelska

### ISSUE THREAD

**Issue by CamillaKaddio2** [kaddio/platform#64]
Tack... på svenska fast resten på engelska

![Skärmavbild 2024-06-13 kl  13 58 34](https://github.com/kaddio/platform/assets/69575123/bb5da0fd-4b1b-417b-b637-be19f4326a20)

**Comment by CamillaKaddio2** [comment]
eller är det för att man skapat konto med land sverige kanske?

**Comment by rhymn** [comment]
Det är för att "Tack" inte fanns översatt i `stores.js`
